/* 마일리지 */
CREATE TABLE MILEAGE (
	MILEAGE_NO NUMBER NOT NULL, /* 내역번호 */
	USER_NO NUMBER NOT NULL, /* 회원번호 */
	REGDATE DATE, /* 일자 */
	POINT NUMBER, /* 입/출금액 */
	DETAIL VARCHAR2(200) /* 내용 */
);

CREATE UNIQUE INDEX PK_MILEAGE
	ON MILEAGE (
		MILEAGE_NO ASC
	);

ALTER TABLE MILEAGE
	ADD
		CONSTRAINT PK_MILEAGE
		PRIMARY KEY (
			MILEAGE_NO
		);
		

/* 쿠폰(여행사) */
CREATE TABLE CUPON_ADMIN (
	CUPON_SERIAL NUMBER NOT NULL, /* 쿠폰번호 */
	CUPON_DETAIL CLOB, /* 쿠폰설명 */
	CUPON_KIND CHAR NOT NULL, /* 할인방식 */
	DISCOUNT NUMBER NOT NULL, /* 금액/퍼센트 */
	REGDATE DATE, /* 쿠폰날짜 */
	DEL_TYPE VARCHAR2(10), /* 만료분류 */
	DELDATE DATE, /* 만료기간 */
	DEL_FLAG CHAR /* 삭제플래스 */
);

CREATE UNIQUE INDEX PK_CUPON_ADMIN
	ON CUPON_ADMIN (
		CUPON_SERIAL ASC
	);

ALTER TABLE CUPON_ADMIN
	ADD
		CONSTRAINT PK_CUPON_ADMIN
		PRIMARY KEY (
			CUPON_SERIAL
		);
		
		
/* 쿠폰(개인) */
CREATE TABLE COUPON (
	CUPON_NO NUMBER NOT NULL, /* 구분번호 */
	CUPON_SERIAL NUMBER NOT NULL, /* 쿠폰번호 */
	USER_NO NUMBER NOT NULL, /* 회원번호 */
	USE_FLAG CHAR, /* 사용여부 */
	REGDATE DATE, /* 발급날짜 */
	DELDATE DATE, /* 만료날짜 */
	USEDATE DATE, /* 사용날짜 */
	DEL_FLAG CHAR /* 만료플래그 */
);

CREATE UNIQUE INDEX PK_COUPON
	ON COUPON (
		CUPON_NO ASC
	);

ALTER TABLE COUPON
	ADD
		CONSTRAINT PK_COUPON
		PRIMARY KEY (
			CUPON_NO
		);