/* 호텔 */
CREATE TABLE HOTEL (
	HOTEL_NO NUMBER NOT NULL, /* 호텔번호 */
	GRADE CHAR, /* 호텔등급 */
	LOCATION VARCHAR2(3000), /* 위치 */
	TEL VARCHAR2(30), /* 연락처 */
	CHECKIN VARCHAR2(200), /* 체크인 */
	CHECKOUT VARCHAR2(200), /* 체크아웃 */
	DETAIL CLOB /* 호텔소개 */
);

CREATE UNIQUE INDEX PK_HOTEL
	ON HOTEL (
		HOTEL_NO ASC
	);

ALTER TABLE HOTEL
	ADD
		CONSTRAINT PK_HOTEL
		PRIMARY KEY (
			HOTEL_NO
		);

/* 호텔 소분류 */
CREATE TABLE HOTEL_DETAIL (
	ROOM_NO NUMBER NOT NULL, /* 분류번호 */
	HOTEL_NO NUMBER NOT NULL, /* 호텔번호 */
	RGRADE CHAR, /* 방등급 */
	ROOM_PRICE NUMBER, /* 방가격 */
	PER_PRICE NUMBER, /* 인당가격 */
	CAPACITY NUMBER /* 수용인원 */
);

CREATE UNIQUE INDEX PK_HOTEL_DETAIL
	ON HOTEL_DETAIL (
		ROOM_NO ASC
	);

ALTER TABLE HOTEL_DETAIL
	ADD
		CONSTRAINT PK_HOTEL_DETAIL
		PRIMARY KEY (
			ROOM_NO
		);
		
/* 항공권 */
CREATE TABLE AIRLINE (
	AIR_NO VARCHAR2(30) NOT NULL, /* 항공권번호 */
	DE_PORT VARCHAR2(300), /* 출발공항 */
	EN_PORT VARCHAR2(300), /* 도착공항 */
	DE_DATE DATE, /* 출발시간 */
	EN_DATE DATE, /* 도착시간 */
	PRICE NUMBER /* 가격 */
);

CREATE UNIQUE INDEX PK_AIRLINE
	ON AIRLINE (
		AIR_NO ASC
	);

ALTER TABLE AIRLINE
	ADD
		CONSTRAINT PK_AIRLINE
		PRIMARY KEY (
			AIR_NO
		);