/* 통계 */
CREATE TABLE CHART (
	CHART_NO NUMBER NOT NULL, /* 통계번호 */
	AREA VARCHAR2(300), /* 지역대분류 */
	SEASON VARCHAR2(300), /* 분기(월) */
	SALES NUMBER NOT NULL, /* 매출 */
	GENDER CHAR, /* 성별 */
	AGE NUMBER /* 나이 */
);

CREATE UNIQUE INDEX PK_CHART
	ON CHART (
		CHART_NO ASC
	);

ALTER TABLE CHART
	ADD
		CONSTRAINT PK_CHART
		PRIMARY KEY (
			CHART_NO
		);

/* 관리자 */
CREATE TABLE MANAGER (
	ADMIN_ID VARCHAR2(60) NOT NULL, /* 아이디 */
	ADMIN_PWD VARCHAR2(60) NOT NULL, /* 비밀번호 */
	NAME VARCHAR2(30), /* 이름 */
	POSITION VARCHAR2(10) DEFAULT 'STEP' NOT NULL, /* 관리자구분 */
	EMAIL1 VARCHAR2(30), /* 이메일1 */
	EMAIL2 VARCHAR2(30), /* 이메일2 */
	HP1 VARCHAR2(3), /* 전화번호1 */
	HP2 VARCHAR2(4), /* 전화번호2 */
	HP3 VARCHAR2(4) /* 전화번호3 */
);

CREATE UNIQUE INDEX PK_MANAGER
	ON MANAGER (
		ADMIN_ID ASC
	);

ALTER TABLE MANAGER
	ADD
		CONSTRAINT PK_MANAGER
		PRIMARY KEY (
			ADMIN_ID
		);

/* 국가 */
CREATE TABLE COUNTRY (
	COUNTRY_CODE VARCHAR2(4) NOT NULL, /* 국가코드 */
	NAME VARCHAR2(100), /* 이름 */
	NAME_ENG VARCHAR2(100), /* 영어이름 */
	REGION VARCHAR2(200) /* 국가분류 */
);

CREATE UNIQUE INDEX PK_COUNTRY
	ON COUNTRY (
		COUNTRY_CODE ASC
	);

ALTER TABLE COUNTRY
	ADD
		CONSTRAINT PK_COUNTRY
		PRIMARY KEY (
			COUNTRY_CODE
		);
		
/* 지역대분류 */
CREATE TABLE AREA (
	AREA_NO NUMBER NOT NULL, /* 지역번호 */
	AREA_C varchar2(4) NOT NULL, /* 지역코드 */
	NAME VARCHAR2(30), /* 지역이름 */
	DETAIL CLOB /* 설명 */
);

CREATE UNIQUE INDEX PK_AREA
	ON AREA (
		AREA_NO ASC
	);

ALTER TABLE AREA
	ADD
		CONSTRAINT PK_AREA
		PRIMARY KEY (
			AREA_NO
		);

/* 지역소분류 */
CREATE TABLE AREA_DETAIL (
	TAG_NO NUMBER NOT NULL, /* 태그번호 */
	AREA_NO NUMBER, /* 지역번호 */
	NAME VARCHAR2(30), /* 소분류이름 */
	KEYWORD VARCHAR2(100) /* 검색 키워드 */
);

CREATE UNIQUE INDEX PK_AREA_DETAIL
	ON AREA_DETAIL (
		TAG_NO ASC
	);

ALTER TABLE AREA_DETAIL
	ADD
		CONSTRAINT PK_AREA_DETAIL
		PRIMARY KEY (
			TAG_NO
		);