/* 후기 */
CREATE TABLE REVIEW (
	REVIEW_NO NUMBER NOT NULL, /* 글번호 */
	USER_NO NUMBER, /* 회원번호 */
	HISTORY_NO NUMBER, /* 내역번호 */
	TITLE VARCHAR2(300), /* 글제목 */
	CONTENT CLOB, /* 글내용 */
	SCORE NUMBER, /* 별점 */
	REGDATE DATE /* 작성일 */
);

CREATE UNIQUE INDEX PK_REVIEW
	ON REVIEW (
		REVIEW_NO ASC
	);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT PK_REVIEW
		PRIMARY KEY (
			REVIEW_NO
		);

/* 댓글 */
CREATE TABLE REPLY (
	REPLY_NO NUMBER NOT NULL, /* 댓글번호 */
	REVIEW_NO NUMBER, /* 글번호 */
	USER_NO NUMBER, /* 회원번호 */
	CONTENT CLOB, /* 댓글내용 */
	REGDATE DATE /* 작성일 */
);

CREATE UNIQUE INDEX PK_REPLY
	ON REPLY (
		REPLY_NO ASC
	);

ALTER TABLE REPLY
	ADD
		CONSTRAINT PK_REPLY
		PRIMARY KEY (
			REPLY_NO
		);
		
		
/* 이용내역 */
CREATE TABLE HISTORY (
	HISTORY_NO NUMBER NOT NULL, /* 내역번호 */
	USER_NO NUMBER, /* 회원번호 */
	STATE VARCHAR2(20), /* 결제상태 */
	PACK_DNO NUMBER, /* 패키지 소분류 번호 */
	PRICE NUMBER, /* 결제금액 */
	REVIEW CHAR(4) DEFAULT 'N' /* 후기여부 */
);

CREATE UNIQUE INDEX PK_HISTORY
	ON HISTORY (
		HISTORY_NO ASC
	);

ALTER TABLE HISTORY
	ADD
		CONSTRAINT PK_HISTORY
		PRIMARY KEY (
			HISTORY_NO
		);
		

