/* 패키지 */
CREATE TABLE PACKAGE (
	PACKAGE_NO NUMBER NOT NULL, /* 패키지번호 */
	NAME VARCHAR2(100), /* 패키지이름 */
	IMG_NAMES VARCHAR2(1000), /* 이미지이름(LIST) */
	IMG_SIZES VARCHAR2(1000), /* D이미지크기(LIST) */
	DESTNATION VARCHAR2(100), /* 여행국가 */
	AIRPORT VARCHAR2(100), /* 이용항공 */
	DAYS VARCHAR2(60), /* 여행기간 */
	DAYS_WEEK VARCHAR2(60) /* 출발요일 */
);

CREATE UNIQUE INDEX PK_PACKAGE
	ON PACKAGE (
		PACKAGE_NO ASC
	);

ALTER TABLE PACKAGE
	ADD
		CONSTRAINT PK_PACKAGE
		PRIMARY KEY (
			PACKAGE_NO
		);
		
		
/* 패키지 상세 */
CREATE TABLE PACKAGE_DETAIL (
	PACKAGE_DNO NUMBER NOT NULL, /* 패키지 소분류 번호 */
	PACKAGE_NO NUMBER NOT NULL, /* 패키지번호 */
	DEPART DATE NOT NULL, /* 한국출발날짜 */
	ENTER DATE NOT NULL, /* 한국도착날짜 */
	MAN NUMBER, /* 성인가격 */
	CHILD NUMBER, /* 유아가격 */
	BABY NUMBER, /* 아동가격 */
	AIRLINE VARCHAR2(300), /* 항공사명 */
	DAYS_DETAIL VARCHAR2(30) NOT NULL, /* 여행기간 */
	SHOPPING CHAR, /* 쇼핑여부 */
	HOTEL_GRADE CHAR, /* 숙소등급 */
	DETAILS CLOB, /* 내용 */
	DESTINATIONS VARCHAR2(1000), /* 경유지 */
	DATES VARCHAR2(1000), /* 시간 */
	TRAVEL_FLAG VARCHAR2(30) /* 여행구분 */
);

CREATE UNIQUE INDEX PK_PACKAGE_DETAIL
	ON PACKAGE_DETAIL (
		PACKAGE_DNO ASC
	);

ALTER TABLE PACKAGE_DETAIL
	ADD
		CONSTRAINT PK_PACKAGE_DETAIL
		PRIMARY KEY (
			PACKAGE_DNO
		);